package com.alokhtoboot.plus;

import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;

public final class MainActivity extends Activity {
    private WebView web; private ProgressBar progress; private static final String START_URL="http://10.10.10.10";
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);web=findViewById(R.id.web);progress=findViewById(R.id.progress);configure();web.loadUrl(START_URL);}
    private void configure(){WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setBuiltInZoomControls(false);s.setDisplayZoomControls(false);s.setMediaPlaybackRequiresUserGesture(false);
        web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){String u=r.getUrl().toString();if(isDownload(u)){enqueueDownload(u,null,null);return true;}return false;}@Override public void onPageStarted(WebView v,String u,android.graphics.Bitmap x){progress.setVisibility(View.VISIBLE);}@Override public void onPageFinished(WebView v,String u){progress.setVisibility(View.GONE);}});
        web.setDownloadListener((url,userAgent,contentDisposition,mimeType,contentLength)->enqueueDownload(url,userAgent,mimeType));}
    private boolean isDownload(String u){String x=u.toLowerCase(Locale.ROOT);return x.contains("/download")||x.matches(".*\\.(mp4|mkv|avi|mov|webm|ts|m3u8|zip|rar|apk|pdf)(\\?.*)?$");}
    private File sdTarget(){File[] ds=getExternalFilesDirs(null);if(ds!=null)for(File d:ds)if(d!=null){String p=d.getAbsolutePath();if(p.contains("/storage/")&&!p.startsWith(Environment.getExternalStorageDirectory().getAbsolutePath())){File root=d.getParentFile();if(root!=null)return new File(root,"downloads");}}File d=getExternalFilesDir(null);return new File(d,"downloads");}
    private void enqueueDownload(String url,String ua,String mime){try{File dir=sdTarget();if(!dir.exists()&&!dir.mkdirs())throw new IOException("Cannot create download directory");String name=URLUtil.guessFileName(url,null,mime);if(name==null||name.trim().isEmpty())name="download.bin";DownloadManager.Request req=new DownloadManager.Request(Uri.parse(url));if(ua!=null)req.addRequestHeader("User-Agent",ua);if(mime!=null&&!mime.isEmpty())req.setMimeType(mime);req.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);req.setTitle(name);req.setDescription("تحميل من الأخطبوط بلس");File out=new File(dir,name);req.setDestinationUri(Uri.fromFile(out));DownloadManager dm=(DownloadManager)getSystemService(DOWNLOAD_SERVICE);if(dm==null)throw new IOException("DownloadManager unavailable");dm.enqueue(req);Toast.makeText(this,"بدأ التحميل: "+name,Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"فشل التحميل: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}
